import type { CollisionIssue, Attachment, DesignReply, StatusRecord } from '@/types'

function createMockAttachments(): Attachment[] {
  return [
    {
      id: 'att_1',
      name: 'BIM碰撞截图_01.png',
      type: 'bim_screenshot',
      url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=BIM%203D%20model%20showing%20fire%20sprinkler%20pipe%20collision%20with%20concrete%20beam%20in%20building%20structure%2C%20technical%20drawing%20style&image_size=square',
      uploadedAt: '2026-06-01T09:30:00',
      uploadedBy: '张工',
      version: 1,
      remark: '初始碰撞检测截图',
    },
    {
      id: 'att_2',
      name: '现场照片_01.jpg',
      type: 'photo',
      url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Construction%20site%20photo%20showing%20fire%20sprinkler%20pipes%20installed%20near%20ceiling%20beams%2C%20industrial%20interior&image_size=square',
      uploadedAt: '2026-06-02T14:20:00',
      uploadedBy: '李工',
      version: 1,
      remark: '现场实际情况照片',
    },
  ]
}

function createMockDesignReplies(): DesignReply[] {
  return [
    {
      id: 'reply_1',
      content: '经复核，此位置梁高调整为600mm，喷淋管可从梁下通过，吊顶标高保持不变。请结构专业确认。',
      repliedBy: '设计院-王工',
      repliedAt: '2026-06-03T10:15:00',
      attachments: [
        {
          id: 'reply_att_1',
          name: '设计变更通知单.pdf',
          type: 'document',
          url: '',
          uploadedAt: '2026-06-03T10:15:00',
          uploadedBy: '设计院-王工',
          version: 1,
          remark: '设计变更单',
        },
      ],
      isLatest: true,
    },
  ]
}

function createStatusHistory(): StatusRecord[] {
  return [
    {
      id: 'hist_1',
      fromStatus: null,
      toStatus: 'draft',
      operator: '张工',
      operateTime: '2026-06-01T09:00:00',
      remark: '创建问题记录',
    },
    {
      id: 'hist_2',
      fromStatus: 'draft',
      toStatus: 'pending',
      operator: '张工',
      operateTime: '2026-06-01T09:30:00',
      remark: '提交审核',
    },
  ]
}

export const mockIssues: CollisionIssue[] = [
  {
    id: 'ISSUE-001',
    title: '3F 走廊喷淋主管与结构梁碰撞',
    floor: '3F',
    system: 'sprinkler',
    category: 'beam',
    location: '3F 东区走廊 A-B轴 / 3-5轴',
    elevation: 2800,
    elevationUnit: 'mm',
    beamHeight: 700,
    responsibleDept: '结构专业',
    assignee: '刘工',
    status: 'pending',
    priority: 'high',
    description: '喷淋主管DN150与结构主梁碰撞，梁底标高2.8m，管底标高2.75m，净高不足。需协调结构专业调整梁高或喷淋专业改管。',
    attachments: createMockAttachments(),
    designReplies: [],
    statusHistory: createStatusHistory(),
    createdAt: '2026-06-01T09:00:00',
    updatedAt: '2026-06-01T09:30:00',
    createdBy: '张工',
  },
  {
    id: 'ISSUE-002',
    title: '2F 空调机房风管与喷淋支管交叉',
    floor: '2F',
    system: 'sprinkler',
    category: 'duct',
    location: '2F 空调机房内 / C-D轴 / 6-8轴',
    elevation: 3200,
    elevationUnit: 'mm',
    responsibleDept: '暖通专业',
    assignee: '赵工',
    status: 'replied',
    priority: 'medium',
    description: '喷淋支管与空调风管标高重叠，风管尺寸1200x500，需确认施工顺序或调整喷淋支管走向。',
    attachments: [
      {
        id: 'att_3',
        name: 'BIM_风管碰撞.png',
        type: 'bim_screenshot',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=BIM%20model%20showing%20HVAC%20duct%20intersecting%20with%20fire%20sprinkler%20pipes%20in%20mechanical%20room%2C%203D%20technical%20visualization&image_size=square',
        uploadedAt: '2026-06-02T11:00:00',
        uploadedBy: '王工',
        version: 1,
        remark: 'BIM模型碰撞点',
      },
    ],
    designReplies: createMockDesignReplies(),
    statusHistory: [
      {
        id: 'hist_3',
        fromStatus: null,
        toStatus: 'draft',
        operator: '王工',
        operateTime: '2026-06-02T10:00:00',
        remark: '创建问题',
      },
      {
        id: 'hist_4',
        fromStatus: 'draft',
        toStatus: 'pending',
        operator: '王工',
        operateTime: '2026-06-02T11:00:00',
        remark: '提交待处理',
      },
      {
        id: 'hist_5',
        fromStatus: 'pending',
        toStatus: 'replied',
        operator: '设计院-李工',
        operateTime: '2026-06-03T10:15:00',
        remark: '设计回复：喷淋管绕风管敷设',
      },
    ],
    createdAt: '2026-06-02T10:00:00',
    updatedAt: '2026-06-03T10:15:00',
    createdBy: '王工',
  },
  {
    id: 'ISSUE-003',
    title: '1F 大堂灯槽与喷淋头位置冲突',
    floor: '1F',
    system: 'sprinkler',
    category: 'light_slot',
    location: '1F 主入口大堂 / 1-3轴 / A-C轴',
    elevation: 3500,
    elevationUnit: 'mm',
    responsibleDept: '装饰专业',
    assignee: '陈工',
    status: 'completed',
    priority: 'high',
    description: '吊顶灯槽造型与喷淋头布置冲突，喷淋头需避开灯槽或调整灯槽造型。已协调装饰专业修改灯槽设计。',
    attachments: [
      {
        id: 'att_4',
        name: '灯槽碰撞示意图.png',
        type: 'bim_screenshot',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Ceiling%20light%20cove%20design%20conflict%20with%20fire%20sprinkler%20head%20placement%2C%20interior%20design%20technical%20drawing&image_size=square',
        uploadedAt: '2026-05-28T15:30:00',
        uploadedBy: '陈工',
        version: 1,
        remark: '碰撞示意图',
      },
      {
        id: 'att_5',
        name: '整改后现场照片.jpg',
        type: 'photo',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Finished%20ceiling%20with%20light%20cove%20and%20properly%20placed%20fire%20sprinkler%20head%2C%20modern%20lobby%20interior&image_size=square',
        uploadedAt: '2026-06-02T16:00:00',
        uploadedBy: '张工',
        version: 2,
        remark: '整改完成后现场照片',
      },
    ],
    designReplies: [
      {
        id: 'reply_2',
        content: '同意调整灯槽造型，喷淋头位置按照消防规范保持不变。灯槽边缘距喷淋头水平距离不小于300mm。',
        repliedBy: '装饰设计-林工',
        repliedAt: '2026-05-30T09:00:00',
        attachments: [],
        isLatest: true,
      },
    ],
    statusHistory: [
      {
        id: 'hist_6',
        fromStatus: null,
        toStatus: 'draft',
        operator: '陈工',
        operateTime: '2026-05-28T15:00:00',
        remark: '创建问题',
      },
      {
        id: 'hist_7',
        fromStatus: 'draft',
        toStatus: 'pending',
        operator: '陈工',
        operateTime: '2026-05-28T15:30:00',
        remark: '提交协调',
      },
      {
        id: 'hist_8',
        fromStatus: 'pending',
        toStatus: 'replied',
        operator: '装饰设计-林工',
        operateTime: '2026-05-30T09:00:00',
        remark: '设计回复：调整灯槽造型',
      },
      {
        id: 'hist_9',
        fromStatus: 'replied',
        toStatus: 'completed',
        operator: '张工',
        operateTime: '2026-06-02T16:00:00',
        remark: '现场确认整改完成',
      },
    ],
    createdAt: '2026-05-28T15:00:00',
    updatedAt: '2026-06-02T16:00:00',
    createdBy: '陈工',
  },
  {
    id: 'ISSUE-004',
    title: 'B1F 车库喷淋干管与电缆桥架碰撞',
    floor: 'B1F',
    system: 'sprinkler',
    category: 'pipe',
    location: 'B1F 地下车库 E区 / 10-15轴',
    elevation: 3800,
    elevationUnit: 'mm',
    responsibleDept: '电气专业',
    assignee: '周工',
    status: 'pending',
    priority: 'medium',
    description: '喷淋干管DN200与强电电缆桥架标高冲突，桥架宽800mm，需综合管线排布。',
    attachments: [
      {
        id: 'att_6',
        name: '车库管线碰撞.png',
        type: 'bim_screenshot',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=BIM%20model%20underground%20parking%20garage%20with%20fire%20sprinkler%20pipe%20collision%20with%20electrical%20cable%20tray%2C%203D%20coordination%20model&image_size=square',
        uploadedAt: '2026-06-04T08:30:00',
        uploadedBy: '周工',
        version: 1,
        remark: '综合管线碰撞检测',
      },
    ],
    designReplies: [],
    statusHistory: [
      {
        id: 'hist_10',
        fromStatus: null,
        toStatus: 'draft',
        operator: '周工',
        operateTime: '2026-06-04T08:00:00',
        remark: '问题录入',
      },
      {
        id: 'hist_11',
        fromStatus: 'draft',
        toStatus: 'pending',
        operator: '周工',
        operateTime: '2026-06-04T08:30:00',
        remark: '提交机电协调',
      },
    ],
    createdAt: '2026-06-04T08:00:00',
    updatedAt: '2026-06-04T08:30:00',
    createdBy: '周工',
  },
  {
    id: 'ISSUE-005',
    title: '5F 办公区次梁与喷淋支管标高冲突',
    floor: '5F',
    system: 'sprinkler',
    category: 'beam',
    location: '5F 开放办公区 / F-H轴 / 4-7轴',
    elevation: 3100,
    elevationUnit: 'mm',
    beamHeight: 500,
    responsibleDept: '结构专业',
    assignee: '刘工',
    status: 'replied',
    priority: 'low',
    description: '喷淋支管穿次梁，梁底净高3.1m，吊顶完成面3.0m，空间紧张。建议调整喷淋支管走向或局部降低吊顶。',
    attachments: [
      {
        id: 'att_7',
        name: '次梁碰撞点.jpg',
        type: 'photo',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Concrete%20secondary%20beam%20in%20office%20ceiling%20with%20fire%20sprinkler%20pipe%20nearby%2C%20construction%20site%20photo&image_size=square',
        uploadedAt: '2026-06-03T13:00:00',
        uploadedBy: '吴工',
        version: 1,
        remark: '现场照片',
      },
    ],
    designReplies: [
      {
        id: 'reply_3',
        content: '结构专业复核：此梁为次梁，可预留套管，管径DN50，套管标高不变。消防专业复核：喷淋支管穿梁满足规范要求。',
        repliedBy: '设计院-结构专业',
        repliedAt: '2026-06-05T09:30:00',
        attachments: [],
        isLatest: true,
      },
    ],
    statusHistory: [
      {
        id: 'hist_12',
        fromStatus: null,
        toStatus: 'draft',
        operator: '吴工',
        operateTime: '2026-06-03T12:00:00',
        remark: '问题提交',
      },
      {
        id: 'hist_13',
        fromStatus: 'draft',
        toStatus: 'pending',
        operator: '吴工',
        operateTime: '2026-06-03T13:00:00',
        remark: '待设计回复',
      },
      {
        id: 'hist_14',
        fromStatus: 'pending',
        toStatus: 'replied',
        operator: '设计院-结构专业',
        operateTime: '2026-06-05T09:30:00',
        remark: '设计回复：预留套管',
      },
    ],
    createdAt: '2026-06-03T12:00:00',
    updatedAt: '2026-06-05T09:30:00',
    createdBy: '吴工',
  },
  {
    id: 'ISSUE-006',
    title: '4F 走廊消火栓立管与新风管交叉',
    floor: '4F',
    system: 'hydrant',
    category: 'duct',
    location: '4F 西区走廊 / 2-3轴 / D轴',
    elevation: 3300,
    elevationUnit: 'mm',
    responsibleDept: '暖通专业',
    assignee: '赵工',
    status: 'completed',
    priority: 'medium',
    description: '消火栓立管DN100与新风管交叉，风管尺寸630x250，已现场调整风管标高避让。',
    attachments: [
      {
        id: 'att_8',
        name: '消火栓立管.jpg',
        type: 'photo',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Fire%20hydrant%20riser%20pipe%20in%20building%20corridor%20with%20HVAC%20ductwork%2C%20construction%20installation&image_size=square',
        uploadedAt: '2026-05-25T10:00:00',
        uploadedBy: '孙工',
        version: 1,
        remark: '现场照片',
      },
      {
        id: 'att_9',
        name: '整改完成照片.jpg',
        type: 'photo',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Completed%20fire%20hydrant%20installation%20with%20properly%20routed%20HVAC%20ducts%20in%20corridor%20ceiling&image_size=square',
        uploadedAt: '2026-05-28T15:00:00',
        uploadedBy: '孙工',
        version: 2,
        remark: '整改完成',
      },
    ],
    designReplies: [
      {
        id: 'reply_4',
        content: '暖通专业同意将新风管标高下调150mm，避让消火栓立管。吊顶标高保持不变。',
        repliedBy: '暖通设计-郑工',
        repliedAt: '2026-05-26T14:00:00',
        attachments: [],
        isLatest: true,
      },
    ],
    statusHistory: [
      {
        id: 'hist_15',
        fromStatus: null,
        toStatus: 'draft',
        operator: '孙工',
        operateTime: '2026-05-25T09:00:00',
        remark: '问题录入',
      },
      {
        id: 'hist_16',
        fromStatus: 'draft',
        toStatus: 'pending',
        operator: '孙工',
        operateTime: '2026-05-25T10:00:00',
        remark: '提交协调',
      },
      {
        id: 'hist_17',
        fromStatus: 'pending',
        toStatus: 'replied',
        operator: '暖通设计-郑工',
        operateTime: '2026-05-26T14:00:00',
        remark: '设计回复：风管下调',
      },
      {
        id: 'hist_18',
        fromStatus: 'replied',
        toStatus: 'completed',
        operator: '孙工',
        operateTime: '2026-05-28T15:00:00',
        remark: '现场整改完成',
      },
    ],
    createdAt: '2026-05-25T09:00:00',
    updatedAt: '2026-05-28T15:00:00',
    createdBy: '孙工',
  },
  {
    id: 'ISSUE-007',
    title: 'B2F 水泵房喷淋泵出口管与梁底距离不足',
    floor: 'B2F',
    system: 'sprinkler',
    category: 'beam',
    location: 'B2F 消防水泵房 / A-B轴 / 1-2轴',
    elevation: 2600,
    elevationUnit: 'mm',
    beamHeight: 900,
    responsibleDept: '结构专业',
    assignee: '刘工',
    status: 'cancelled',
    priority: 'high',
    description: '喷淋泵出口管DN200距梁底仅50mm，安装空间不足。经复核，水泵选型调整后管道尺寸减小，问题自然消除。',
    attachments: [
      {
        id: 'att_10',
        name: '水泵房BIM图.png',
        type: 'bim_screenshot',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=BIM%20model%20of%20fire%20pump%20room%20with%20sprinkler%20pipes%20and%20concrete%20beams%2C%20technical%203D%20visualization&image_size=square',
        uploadedAt: '2026-05-20T11:00:00',
        uploadedBy: '黄工',
        version: 1,
        remark: '初始设计',
      },
    ],
    designReplies: [],
    statusHistory: [
      {
        id: 'hist_19',
        fromStatus: null,
        toStatus: 'draft',
        operator: '黄工',
        operateTime: '2026-05-20T10:00:00',
        remark: '问题录入',
      },
      {
        id: 'hist_20',
        fromStatus: 'draft',
        toStatus: 'pending',
        operator: '黄工',
        operateTime: '2026-05-20T11:00:00',
        remark: '待协调',
      },
      {
        id: 'hist_21',
        fromStatus: 'pending',
        toStatus: 'cancelled',
        operator: '黄工',
        operateTime: '2026-05-22T16:00:00',
        remark: '水泵选型调整，问题自动消除',
      },
    ],
    createdAt: '2026-05-20T10:00:00',
    updatedAt: '2026-05-22T16:00:00',
    createdBy: '黄工',
  },
  {
    id: 'ISSUE-008',
    title: '6F 会议室灯槽内喷淋头布置间距超标',
    floor: '6F',
    system: 'sprinkler',
    category: 'light_slot',
    location: '6F 大会议室 / 5-8轴 / C-F轴',
    elevation: 3400,
    elevationUnit: 'mm',
    responsibleDept: '装饰专业',
    assignee: '陈工',
    status: 'pending',
    priority: 'high',
    description: '会议室吊顶灯槽造型复杂，部分区域喷淋头布置间距超过规范要求的3.6m。需增设喷淋头或调整灯槽造型。',
    attachments: [
      {
        id: 'att_11',
        name: '会议室吊顶图.png',
        type: 'bim_screenshot',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Conference%20room%20ceiling%20design%20with%20decorative%20light%20cove%20and%20fire%20sprinkler%20heads%2C%20interior%20design%20rendering&image_size=square',
        uploadedAt: '2026-06-05T09:00:00',
        uploadedBy: '林工',
        version: 1,
        remark: '吊顶平面图',
      },
    ],
    designReplies: [],
    statusHistory: [
      {
        id: 'hist_22',
        fromStatus: null,
        toStatus: 'draft',
        operator: '林工',
        operateTime: '2026-06-05T08:30:00',
        remark: '问题录入',
      },
      {
        id: 'hist_23',
        fromStatus: 'draft',
        toStatus: 'pending',
        operator: '林工',
        operateTime: '2026-06-05T09:00:00',
        remark: '待装饰专业协调',
      },
    ],
    createdAt: '2026-06-05T08:30:00',
    updatedAt: '2026-06-05T09:00:00',
    createdBy: '林工',
  },
]
