// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $batches from "./routes/batches.tsx";
import * as $component_id_ from "./routes/component/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $tasks from "./routes/tasks.tsx";
import * as $BatchManager from "./islands/BatchManager.tsx";
import * as $ComponentDetail from "./islands/ComponentDetail.tsx";
import * as $ComponentList from "./islands/ComponentList.tsx";
import * as $MoistureModal from "./islands/MoistureModal.tsx";
import * as $OfflineQueueBanner from "./islands/OfflineQueueBanner.tsx";
import * as $RecheckTaskList from "./islands/RecheckTaskList.tsx";
import * as $SwabMap from "./islands/SwabMap.tsx";
import * as $UserRoleSwitch from "./islands/UserRoleSwitch.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/batches.tsx": $batches,
    "./routes/component/[id].tsx": $component_id_,
    "./routes/index.tsx": $index,
    "./routes/tasks.tsx": $tasks,
  },
  islands: {
    "./islands/BatchManager.tsx": $BatchManager,
    "./islands/ComponentDetail.tsx": $ComponentDetail,
    "./islands/ComponentList.tsx": $ComponentList,
    "./islands/MoistureModal.tsx": $MoistureModal,
    "./islands/OfflineQueueBanner.tsx": $OfflineQueueBanner,
    "./islands/RecheckTaskList.tsx": $RecheckTaskList,
    "./islands/SwabMap.tsx": $SwabMap,
    "./islands/UserRoleSwitch.tsx": $UserRoleSwitch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
