import { FollowUpRecord, AuditLog } from './types';

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    recordId: 'rec-001',
    operatorId: 'nurse-01',
    operatorName: '王护士',
    action: 'create',
    changes: [
      { field: 'parentVisible.infantName', oldValue: null, newValue: '李小明' },
      { field: 'parentVisible.vaccineBatch', oldValue: null, newValue: 'HB20240301A' },
    ],
    timestamp: '2025-06-01 09:15:00',
  },
  {
    id: 'audit-002',
    recordId: 'rec-001',
    operatorId: 'nurse-02',
    operatorName: '张护士',
    action: 'update',
    changes: [
      { field: 'parentVisible.nextFollowUpDate', oldValue: '2025-07-01', newValue: '2025-07-15' },
      { field: 'internal.internalNotes', oldValue: '', newValue: '家长要求延后两周' },
    ],
    timestamp: '2025-06-02 14:30:00',
  },
  {
    id: 'audit-003',
    recordId: 'rec-001',
    operatorId: 'teacher-01',
    operatorName: '赵保健老师',
    action: 'review',
    changes: [
      { field: 'status', oldValue: 'pending_review', newValue: 'reviewed' },
      { field: 'reviewResult', oldValue: null, newValue: 'pass' },
    ],
    timestamp: '2025-06-03 10:00:00',
  },
  {
    id: 'audit-004',
    recordId: 'rec-002',
    operatorId: 'nurse-01',
    operatorName: '王护士',
    action: 'manual_entry',
    changes: [
      { field: 'isManualEntry', oldValue: 'false', newValue: 'true' },
      { field: 'parentVisible.infantName', oldValue: null, newValue: '陈补补' },
      { field: 'parentVisible.vaccineBatch', oldValue: null, newValue: 'BCG20240502B' },
      { field: 'internal.internalNotes', oldValue: null, newValue: '手工补录：原系统录入遗漏，纸质档案第7页佐证' },
    ],
    timestamp: '2025-06-04 16:45:00',
  },
  {
    id: 'audit-005',
    recordId: 'rec-003',
    operatorId: 'nurse-03',
    operatorName: '刘护士',
    action: 'create',
    changes: [
      { field: 'parentVisible.infantName', oldValue: null, newValue: '王缺缺' },
    ],
    timestamp: '2025-06-05 08:20:00',
  },
];

export const mockRecords: FollowUpRecord[] = [
  {
    id: 'rec-001',
    parentVisible: {
      infantName: '李小明',
      gender: 'male',
      birthDate: '2024-11-15',
      guardianName: '李国强',
      guardianPhone: '138****1234',
      vaccineName: '乙肝疫苗第二剂',
      vaccineBatch: 'HB20240301A',
      vaccinationDate: '2025-06-01',
      vaccinationSite: '西门社区卫生服务中心',
      nextFollowUpDate: '2025-07-15',
      publicRemarks: '接种后观察30分钟无异常',
    },
    internal: {
      medicalRecordNo: 'MR20241115-001',
      nurseId: 'nurse-01',
      nurseName: '王护士',
      internalNotes: '家长要求延后两周，下次随访注意提醒',
      abnormalSymptoms: [],
      contraindications: [],
    },
    status: 'reviewed',
    dataQuality: 'normal',
    isManualEntry: false,
    createdAt: '2025-06-01 09:15:00',
    createdBy: '王护士',
    updatedAt: '2025-06-02 14:30:00',
    updatedBy: '张护士',
    reviewedAt: '2025-06-03 10:00:00',
    reviewedBy: '赵保健老师',
    reviewResult: 'pass',
    reviewComments: '材料完整，记录规范',
    anomalies: [],
    auditLogIds: ['audit-001', 'audit-002', 'audit-003'],
  },
  {
    id: 'rec-002',
    parentVisible: {
      infantName: '陈补补',
      gender: 'female',
      birthDate: '2024-08-20',
      guardianName: '陈大海',
      guardianPhone: '139****5678',
      vaccineName: '卡介苗',
      vaccineBatch: 'BCG20240502B',
      vaccinationDate: '2024-09-01',
      vaccinationSite: '西门社区卫生服务中心',
      nextFollowUpDate: '2025-07-01',
      publicRemarks: '接种部位有轻微红肿，属正常反应',
    },
    internal: {
      medicalRecordNo: 'MR20240820-007',
      nurseId: 'nurse-01',
      nurseName: '王护士',
      internalNotes: '【手工补录】原系统录入遗漏，纸质档案第7页佐证。因2024年9月系统升级造成数据丢失，已与家长电话核实信息无误。补录原因：批次追溯专项检查发现缺口。',
      abnormalSymptoms: ['接种部位红肿'],
      contraindications: [],
    },
    status: 'pending_review',
    dataQuality: 'normal',
    isManualEntry: true,
    createdAt: '2025-06-04 16:45:00',
    createdBy: '王护士',
    updatedAt: '2025-06-04 16:45:00',
    updatedBy: '王护士',
    reviewedAt: null,
    reviewedBy: null,
    reviewResult: null,
    reviewComments: '',
    anomalies: [],
    auditLogIds: ['audit-004'],
  },
  {
    id: 'rec-003',
    parentVisible: {
      infantName: '王缺缺',
      gender: 'male',
      birthDate: '2025-01-10',
      guardianName: '王建国',
      guardianPhone: '137****9012',
      vaccineName: '百白破疫苗第一剂',
      vaccineBatch: 'DPT20250103C',
      vaccinationDate: '2025-06-05',
      vaccinationSite: '西门社区卫生服务中心',
      nextFollowUpDate: '2025-08-05',
      publicRemarks: '',
    },
    internal: {
      medicalRecordNo: 'MR20250110-023',
      nurseId: 'nurse-03',
      nurseName: '刘护士',
      internalNotes: '材料不全，暂存',
      abnormalSymptoms: [],
      contraindications: [],
    },
    status: 'draft',
    dataQuality: 'missing_pages',
    isManualEntry: false,
    createdAt: '2025-06-05 08:20:00',
    createdBy: '刘护士',
    updatedAt: '2025-06-05 08:20:00',
    updatedBy: '刘护士',
    reviewedAt: null,
    reviewedBy: null,
    reviewResult: null,
    reviewComments: '',
    anomalies: [
      {
        type: 'missing_pages',
        description: '纸质材料缺页',
        detail: '家长带来的接种手册缺少第5-6页（即2025年3月-4月的接种记录页），已告知家长下次带来补交。当前录入信息仅依据家长口述和接种卡存根。',
        reportedAt: '2025-06-05 08:25:00',
        reportedBy: '刘护士',
      },
    ],
    auditLogIds: ['audit-005'],
  },
  {
    id: 'rec-004',
    parentVisible: {
      infantName: '赵正常',
      gender: 'female',
      birthDate: '2024-12-01',
      guardianName: '赵志明',
      guardianPhone: '136****3456',
      vaccineName: '脊灰灭活疫苗第二剂',
      vaccineBatch: 'IPV20241208D',
      vaccinationDate: '2025-06-02',
      vaccinationSite: '西门社区卫生服务中心',
      nextFollowUpDate: '2025-08-02',
      publicRemarks: '无异常',
    },
    internal: {
      medicalRecordNo: 'MR20241201-045',
      nurseId: 'nurse-02',
      nurseName: '张护士',
      internalNotes: '',
      abnormalSymptoms: [],
      contraindications: ['鸡蛋过敏史（已告知家长脊灰疫苗注意事项）'],
    },
    status: 'reviewed',
    dataQuality: 'normal',
    isManualEntry: false,
    createdAt: '2025-06-02 10:30:00',
    createdBy: '张护士',
    updatedAt: '2025-06-03 11:00:00',
    updatedBy: '赵保健老师',
    reviewedAt: '2025-06-03 11:00:00',
    reviewedBy: '赵保健老师',
    reviewResult: 'pass',
    reviewComments: '记录完整',
    anomalies: [],
    auditLogIds: [],
  },
  {
    id: 'rec-005',
    parentVisible: {
      infantName: '孙复核',
      gender: 'male',
      birthDate: '2025-02-14',
      guardianName: '孙伟',
      guardianPhone: '135****7890',
      vaccineName: '麻腮风疫苗第一剂',
      vaccineBatch: 'MMR20250120E',
      vaccinationDate: '2025-06-06',
      vaccinationSite: '西门社区卫生服务中心',
      nextFollowUpDate: '2025-09-06',
      publicRemarks: '',
    },
    internal: {
      medicalRecordNo: 'MR20250214-067',
      nurseId: 'nurse-01',
      nurseName: '王护士',
      internalNotes: '批次号存疑，待复核',
      abnormalSymptoms: [],
      contraindications: [],
    },
    status: 'pending_review',
    dataQuality: 'normal',
    isManualEntry: false,
    createdAt: '2025-06-06 15:00:00',
    createdBy: '王护士',
    updatedAt: '2025-06-06 15:00:00',
    updatedBy: '王护士',
    reviewedAt: null,
    reviewedBy: null,
    reviewResult: null,
    reviewComments: '',
    anomalies: [],
    auditLogIds: [],
  },
];
