/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { KeyboardAction, KeyboardMapping, TouchRecord } from "./utils/types";
import { PinValidationResult } from "./components/pin-validator/pin-validator";
export { KeyboardAction, KeyboardMapping, TouchRecord } from "./utils/types";
export { PinValidationResult } from "./components/pin-validator/pin-validator";
export namespace Components {
    interface ControversyMode {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default 3
         */
        "maxLookback": number;
        "resetSelection": () => Promise<void>;
        /**
          * @default []
         */
        "touches": TouchRecord[];
    }
    interface CountdownTimer {
        /**
          * @default false
         */
        "autoStart": boolean;
        /**
          * @default false
         */
        "fullscreen": boolean;
        /**
          * @default 45
         */
        "initialSeconds": number;
        /**
          * @default '局间休息'
         */
        "label": string;
        "pause": () => Promise<void>;
        "reset": () => Promise<void>;
        "start": () => Promise<void>;
    }
    interface KeyboardMapper {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default {   F1: 'LEFT_VALID',   F2: 'RIGHT_VALID',   F3: 'LEFT_OFFTARGET',   F4: 'RIGHT_OFFTARGET',   F5: 'SIMULTANEOUS',   F6: 'NO_TOUCH',   F7: 'LEFT_YELLOW',   F8: 'RIGHT_YELLOW',   F9: 'LEFT_RED',   F10: 'RIGHT_RED',   F11: 'LEFT_BLACK',   F12: 'RIGHT_BLACK',   Backspace: 'UNDO_LAST',   Space: 'PAUSE_PERIOD',   KeyB: 'START_BREAK',   KeyC: 'CONTROVERSY_TOGGLE',   KeyE: 'REQUEST_SCORE_EDIT',   KeyS: 'SEAL_BOUT', }
         */
        "mapping": KeyboardMapping;
    }
    interface OfflineCache {
        "clearAll": () => Promise<void>;
        "listBouts": () => Promise<Array<{ id: string; savedAt: number; }>>;
        "loadBout": (boutId: string) => Promise<any | null>;
        "queueUpload": (payload: any) => Promise<void>;
        "removeBout": (boutId: string) => Promise<boolean>;
        "saveBout": (boutId: string, state: any) => Promise<boolean>;
        "syncQueue": () => Promise<{ success: number; failed: number; }>;
        /**
          * @default ''
         */
        "uploadEndpoint": string;
    }
    interface PinValidator {
        /**
          * @default [   { pin: '1111', name: '主裁判' },   { pin: '2222', name: '副裁判' },   { pin: '3333', name: '裁判长' }, ]
         */
        "accounts": RefereeAccount[];
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default '改分需双裁判 PIN 验证'
         */
        "panelTitle": string;
        /**
          * @default 2
         */
        "requiredReferees": number;
        "reset": () => Promise<void>;
    }
    interface RefereePanel {
    }
    interface ScoreDisplay {
        "applyCard": (side: "left" | "right", type: "yellow" | "red" | "black") => Promise<void>;
        /**
          * @default '左方'
         */
        "leftName": string;
        /**
          * @default false
         */
        "leftPriority": boolean;
        /**
          * @default 0
         */
        "leftScore": number;
        /**
          * @default 1
         */
        "period": number;
        /**
          * @default '右方'
         */
        "rightName": string;
        /**
          * @default false
         */
        "rightPriority": boolean;
        /**
          * @default 0
         */
        "rightScore": number;
        /**
          * @default 15
         */
        "targetScore": number;
        /**
          * @default 180
         */
        "timeRemaining": number;
        "triggerFlash": (side: "left" | "right" | "both") => Promise<void>;
    }
    interface XmlExporter {
        /**
          * @default ''
         */
        "associationEndpoint": string;
        /**
          * @default false
         */
        "autoUpload": boolean;
        /**
          * @default null
         */
        "boutState": any;
        "buildXml": () => Promise<string>;
        "download": () => Promise<string>;
        "exportAndUpload": () => Promise<{ xml: string; uploaded: boolean; }>;
        "uploadToAssociation": () => Promise<boolean>;
    }
}
export interface ControversyModeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLControversyModeElement;
}
export interface CountdownTimerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCountdownTimerElement;
}
export interface KeyboardMapperCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKeyboardMapperElement;
}
export interface OfflineCacheCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOfflineCacheElement;
}
export interface PinValidatorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPinValidatorElement;
}
export interface XmlExporterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXmlExporterElement;
}
declare global {
    interface HTMLControversyModeElementEventMap {
        "exitRequested": void;
        "annotationAdded": { touchId: string; text: string };
    }
    interface HTMLControversyModeElement extends Components.ControversyMode, HTMLStencilElement {
        addEventListener<K extends keyof HTMLControversyModeElementEventMap>(type: K, listener: (this: HTMLControversyModeElement, ev: ControversyModeCustomEvent<HTMLControversyModeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLControversyModeElementEventMap>(type: K, listener: (this: HTMLControversyModeElement, ev: ControversyModeCustomEvent<HTMLControversyModeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLControversyModeElement: {
        prototype: HTMLControversyModeElement;
        new (): HTMLControversyModeElement;
    };
    interface HTMLCountdownTimerElementEventMap {
        "timerEnded": void;
        "timerTick": number;
    }
    interface HTMLCountdownTimerElement extends Components.CountdownTimer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCountdownTimerElementEventMap>(type: K, listener: (this: HTMLCountdownTimerElement, ev: CountdownTimerCustomEvent<HTMLCountdownTimerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCountdownTimerElementEventMap>(type: K, listener: (this: HTMLCountdownTimerElement, ev: CountdownTimerCustomEvent<HTMLCountdownTimerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCountdownTimerElement: {
        prototype: HTMLCountdownTimerElement;
        new (): HTMLCountdownTimerElement;
    };
    interface HTMLKeyboardMapperElementEventMap {
        "actionFired": KeyboardAction;
    }
    interface HTMLKeyboardMapperElement extends Components.KeyboardMapper, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKeyboardMapperElementEventMap>(type: K, listener: (this: HTMLKeyboardMapperElement, ev: KeyboardMapperCustomEvent<HTMLKeyboardMapperElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKeyboardMapperElementEventMap>(type: K, listener: (this: HTMLKeyboardMapperElement, ev: KeyboardMapperCustomEvent<HTMLKeyboardMapperElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKeyboardMapperElement: {
        prototype: HTMLKeyboardMapperElement;
        new (): HTMLKeyboardMapperElement;
    };
    interface HTMLOfflineCacheElementEventMap {
        "cachedLoaded": any;
        "syncComplete": { success: number; failed: number };
    }
    interface HTMLOfflineCacheElement extends Components.OfflineCache, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOfflineCacheElementEventMap>(type: K, listener: (this: HTMLOfflineCacheElement, ev: OfflineCacheCustomEvent<HTMLOfflineCacheElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOfflineCacheElementEventMap>(type: K, listener: (this: HTMLOfflineCacheElement, ev: OfflineCacheCustomEvent<HTMLOfflineCacheElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOfflineCacheElement: {
        prototype: HTMLOfflineCacheElement;
        new (): HTMLOfflineCacheElement;
    };
    interface HTMLPinValidatorElementEventMap {
        "validated": PinValidationResult;
        "cancelled": void;
    }
    interface HTMLPinValidatorElement extends Components.PinValidator, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPinValidatorElementEventMap>(type: K, listener: (this: HTMLPinValidatorElement, ev: PinValidatorCustomEvent<HTMLPinValidatorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPinValidatorElementEventMap>(type: K, listener: (this: HTMLPinValidatorElement, ev: PinValidatorCustomEvent<HTMLPinValidatorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPinValidatorElement: {
        prototype: HTMLPinValidatorElement;
        new (): HTMLPinValidatorElement;
    };
    interface HTMLRefereePanelElement extends Components.RefereePanel, HTMLStencilElement {
    }
    var HTMLRefereePanelElement: {
        prototype: HTMLRefereePanelElement;
        new (): HTMLRefereePanelElement;
    };
    interface HTMLScoreDisplayElement extends Components.ScoreDisplay, HTMLStencilElement {
    }
    var HTMLScoreDisplayElement: {
        prototype: HTMLScoreDisplayElement;
        new (): HTMLScoreDisplayElement;
    };
    interface HTMLXmlExporterElementEventMap {
        "exportComplete": { xml: string; uploaded: boolean };
        "uploadFailed": { error: string };
    }
    interface HTMLXmlExporterElement extends Components.XmlExporter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXmlExporterElementEventMap>(type: K, listener: (this: HTMLXmlExporterElement, ev: XmlExporterCustomEvent<HTMLXmlExporterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXmlExporterElementEventMap>(type: K, listener: (this: HTMLXmlExporterElement, ev: XmlExporterCustomEvent<HTMLXmlExporterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXmlExporterElement: {
        prototype: HTMLXmlExporterElement;
        new (): HTMLXmlExporterElement;
    };
    interface HTMLElementTagNameMap {
        "controversy-mode": HTMLControversyModeElement;
        "countdown-timer": HTMLCountdownTimerElement;
        "keyboard-mapper": HTMLKeyboardMapperElement;
        "offline-cache": HTMLOfflineCacheElement;
        "pin-validator": HTMLPinValidatorElement;
        "referee-panel": HTMLRefereePanelElement;
        "score-display": HTMLScoreDisplayElement;
        "xml-exporter": HTMLXmlExporterElement;
    }
}
declare namespace LocalJSX {
    interface ControversyMode {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default 3
         */
        "maxLookback"?: number;
        "onAnnotationAdded"?: (event: ControversyModeCustomEvent<{ touchId: string; text: string }>) => void;
        "onExitRequested"?: (event: ControversyModeCustomEvent<void>) => void;
        /**
          * @default []
         */
        "touches"?: TouchRecord[];
    }
    interface CountdownTimer {
        /**
          * @default false
         */
        "autoStart"?: boolean;
        /**
          * @default false
         */
        "fullscreen"?: boolean;
        /**
          * @default 45
         */
        "initialSeconds"?: number;
        /**
          * @default '局间休息'
         */
        "label"?: string;
        "onTimerEnded"?: (event: CountdownTimerCustomEvent<void>) => void;
        "onTimerTick"?: (event: CountdownTimerCustomEvent<number>) => void;
    }
    interface KeyboardMapper {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default {   F1: 'LEFT_VALID',   F2: 'RIGHT_VALID',   F3: 'LEFT_OFFTARGET',   F4: 'RIGHT_OFFTARGET',   F5: 'SIMULTANEOUS',   F6: 'NO_TOUCH',   F7: 'LEFT_YELLOW',   F8: 'RIGHT_YELLOW',   F9: 'LEFT_RED',   F10: 'RIGHT_RED',   F11: 'LEFT_BLACK',   F12: 'RIGHT_BLACK',   Backspace: 'UNDO_LAST',   Space: 'PAUSE_PERIOD',   KeyB: 'START_BREAK',   KeyC: 'CONTROVERSY_TOGGLE',   KeyE: 'REQUEST_SCORE_EDIT',   KeyS: 'SEAL_BOUT', }
         */
        "mapping"?: KeyboardMapping;
        "onActionFired"?: (event: KeyboardMapperCustomEvent<KeyboardAction>) => void;
    }
    interface OfflineCache {
        "onCachedLoaded"?: (event: OfflineCacheCustomEvent<any>) => void;
        "onSyncComplete"?: (event: OfflineCacheCustomEvent<{ success: number; failed: number }>) => void;
        /**
          * @default ''
         */
        "uploadEndpoint"?: string;
    }
    interface PinValidator {
        /**
          * @default [   { pin: '1111', name: '主裁判' },   { pin: '2222', name: '副裁判' },   { pin: '3333', name: '裁判长' }, ]
         */
        "accounts"?: RefereeAccount[];
        "onCancelled"?: (event: PinValidatorCustomEvent<void>) => void;
        "onValidated"?: (event: PinValidatorCustomEvent<PinValidationResult>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default '改分需双裁判 PIN 验证'
         */
        "panelTitle"?: string;
        /**
          * @default 2
         */
        "requiredReferees"?: number;
    }
    interface RefereePanel {
    }
    interface ScoreDisplay {
        /**
          * @default '左方'
         */
        "leftName"?: string;
        /**
          * @default false
         */
        "leftPriority"?: boolean;
        /**
          * @default 0
         */
        "leftScore"?: number;
        /**
          * @default 1
         */
        "period"?: number;
        /**
          * @default '右方'
         */
        "rightName"?: string;
        /**
          * @default false
         */
        "rightPriority"?: boolean;
        /**
          * @default 0
         */
        "rightScore"?: number;
        /**
          * @default 15
         */
        "targetScore"?: number;
        /**
          * @default 180
         */
        "timeRemaining"?: number;
    }
    interface XmlExporter {
        /**
          * @default ''
         */
        "associationEndpoint"?: string;
        /**
          * @default false
         */
        "autoUpload"?: boolean;
        /**
          * @default null
         */
        "boutState"?: any;
        "onExportComplete"?: (event: XmlExporterCustomEvent<{ xml: string; uploaded: boolean }>) => void;
        "onUploadFailed"?: (event: XmlExporterCustomEvent<{ error: string }>) => void;
    }

    interface ControversyModeAttributes {
        "active": boolean;
        "maxLookback": number;
    }
    interface CountdownTimerAttributes {
        "initialSeconds": number;
        "fullscreen": boolean;
        "autoStart": boolean;
        "label": string;
    }
    interface KeyboardMapperAttributes {
        "disabled": boolean;
    }
    interface OfflineCacheAttributes {
        "uploadEndpoint": string;
    }
    interface PinValidatorAttributes {
        "requiredReferees": number;
        "panelTitle": string;
        "open": boolean;
    }
    interface ScoreDisplayAttributes {
        "leftName": string;
        "rightName": string;
        "leftScore": number;
        "rightScore": number;
        "targetScore": number;
        "period": number;
        "timeRemaining": number;
        "leftPriority": boolean;
        "rightPriority": boolean;
    }
    interface XmlExporterAttributes {
        "boutState": string;
        "associationEndpoint": string;
        "autoUpload": boolean;
    }

    interface IntrinsicElements {
        "controversy-mode": Omit<ControversyMode, keyof ControversyModeAttributes> & { [K in keyof ControversyMode & keyof ControversyModeAttributes]?: ControversyMode[K] } & { [K in keyof ControversyMode & keyof ControversyModeAttributes as `attr:${K}`]?: ControversyModeAttributes[K] } & { [K in keyof ControversyMode & keyof ControversyModeAttributes as `prop:${K}`]?: ControversyMode[K] };
        "countdown-timer": Omit<CountdownTimer, keyof CountdownTimerAttributes> & { [K in keyof CountdownTimer & keyof CountdownTimerAttributes]?: CountdownTimer[K] } & { [K in keyof CountdownTimer & keyof CountdownTimerAttributes as `attr:${K}`]?: CountdownTimerAttributes[K] } & { [K in keyof CountdownTimer & keyof CountdownTimerAttributes as `prop:${K}`]?: CountdownTimer[K] };
        "keyboard-mapper": Omit<KeyboardMapper, keyof KeyboardMapperAttributes> & { [K in keyof KeyboardMapper & keyof KeyboardMapperAttributes]?: KeyboardMapper[K] } & { [K in keyof KeyboardMapper & keyof KeyboardMapperAttributes as `attr:${K}`]?: KeyboardMapperAttributes[K] } & { [K in keyof KeyboardMapper & keyof KeyboardMapperAttributes as `prop:${K}`]?: KeyboardMapper[K] };
        "offline-cache": Omit<OfflineCache, keyof OfflineCacheAttributes> & { [K in keyof OfflineCache & keyof OfflineCacheAttributes]?: OfflineCache[K] } & { [K in keyof OfflineCache & keyof OfflineCacheAttributes as `attr:${K}`]?: OfflineCacheAttributes[K] } & { [K in keyof OfflineCache & keyof OfflineCacheAttributes as `prop:${K}`]?: OfflineCache[K] };
        "pin-validator": Omit<PinValidator, keyof PinValidatorAttributes> & { [K in keyof PinValidator & keyof PinValidatorAttributes]?: PinValidator[K] } & { [K in keyof PinValidator & keyof PinValidatorAttributes as `attr:${K}`]?: PinValidatorAttributes[K] } & { [K in keyof PinValidator & keyof PinValidatorAttributes as `prop:${K}`]?: PinValidator[K] };
        "referee-panel": RefereePanel;
        "score-display": Omit<ScoreDisplay, keyof ScoreDisplayAttributes> & { [K in keyof ScoreDisplay & keyof ScoreDisplayAttributes]?: ScoreDisplay[K] } & { [K in keyof ScoreDisplay & keyof ScoreDisplayAttributes as `attr:${K}`]?: ScoreDisplayAttributes[K] } & { [K in keyof ScoreDisplay & keyof ScoreDisplayAttributes as `prop:${K}`]?: ScoreDisplay[K] };
        "xml-exporter": Omit<XmlExporter, keyof XmlExporterAttributes> & { [K in keyof XmlExporter & keyof XmlExporterAttributes]?: XmlExporter[K] } & { [K in keyof XmlExporter & keyof XmlExporterAttributes as `attr:${K}`]?: XmlExporterAttributes[K] } & { [K in keyof XmlExporter & keyof XmlExporterAttributes as `prop:${K}`]?: XmlExporter[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "controversy-mode": LocalJSX.IntrinsicElements["controversy-mode"] & JSXBase.HTMLAttributes<HTMLControversyModeElement>;
            "countdown-timer": LocalJSX.IntrinsicElements["countdown-timer"] & JSXBase.HTMLAttributes<HTMLCountdownTimerElement>;
            "keyboard-mapper": LocalJSX.IntrinsicElements["keyboard-mapper"] & JSXBase.HTMLAttributes<HTMLKeyboardMapperElement>;
            "offline-cache": LocalJSX.IntrinsicElements["offline-cache"] & JSXBase.HTMLAttributes<HTMLOfflineCacheElement>;
            "pin-validator": LocalJSX.IntrinsicElements["pin-validator"] & JSXBase.HTMLAttributes<HTMLPinValidatorElement>;
            "referee-panel": LocalJSX.IntrinsicElements["referee-panel"] & JSXBase.HTMLAttributes<HTMLRefereePanelElement>;
            "score-display": LocalJSX.IntrinsicElements["score-display"] & JSXBase.HTMLAttributes<HTMLScoreDisplayElement>;
            "xml-exporter": LocalJSX.IntrinsicElements["xml-exporter"] & JSXBase.HTMLAttributes<HTMLXmlExporterElement>;
        }
    }
}
