import type { Sample } from '@/types'
import { generateId } from '@/utils/date'

const SEAL_PHOTO_AL = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=aluminum%20panel%20curtain%20wall%20silver%20grey%20color%20sample%20board%20with%20color%20swatch%20industrial%20material&image_size=square'
const SEAL_PHOTO_BRONZE = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=bronze%20anodized%20aluminum%20curtain%20wall%20panel%20color%20sample%20swatch%20board&image_size=square'
const SEAL_PHOTO_STONE = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=natural%20granite%20stone%20cladding%20panel%20sample%20grey%20vein%20texture&image_size=square'
const SEAL_PHOTO_GLASS = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=tempered%20low-e%20glass%20curtain%20wall%20panel%20reflective%20blue%20sample&image_size=square'

const ENTRY_PHOTO_OK = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=aluminum%20panel%20delivery%20site%20inspection%20stacked%20panels%20with%20protective%20film&image_size=square'
const ENTRY_PHOTO_BIAS = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=aluminum%20panel%20color%20mismatch%20comparison%20two%20panels%20side%20by%20side%20slight%20color%20difference&image_size=square'
const ENTRY_PHOTO_STONE = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=granite%20stone%20panels%20pallet%20delivery%20construction%20site&image_size=square'
const ENTRY_PHOTO_GLASS = 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=glass%20curtain%20wall%20unit%20delivery%20crate%20construction%20site%20inspection&image_size=square'

function dateStr(daysAgo: number): string {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  return d.toISOString().slice(0, 10)
}

function ts(daysAgo: number): string {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  return d.toISOString()
}

export function getMockSamples(): Sample[] {
  return [
    {
      id: generateId('sample'),
      sampleNo: 'CW-AL-2025-001',
      version: 'V2.1',
      materialType: '氟碳喷涂铝板',
      specification: '3mm 银灰色 氟碳三涂 PVDF',
      manufacturer: '华南铝业集团有限公司',
      manufacturerContact: '张经理',
      manufacturerPhone: '13800138001',
      sealPhoto: SEAL_PHOTO_AL,
      sealDate: dateStr(45),
      sealConfirmer: '李明（业主代表）',
      remark: '东塔南立面标准层铝板，与色卡AL-S-017一致，哑光表面',
      status: 'available',
      createdAt: ts(50),
      updatedAt: ts(10),
      batches: [
        {
          id: generateId('batch'),
          sampleId: '',
          batchNo: 'HN-20250315-A1',
          entryBatchNo: 'JC-AL-001',
          entryPhoto: ENTRY_PHOTO_OK,
          entryDate: dateStr(20),
          quantity: '320片 / 1,280㎡',
          remark: '第一批进场，数量核对无误',
        },
        {
          id: generateId('batch'),
          sampleId: '',
          batchNo: 'HN-20250402-B2',
          entryBatchNo: 'JC-AL-014',
          entryPhoto: ENTRY_PHOTO_BIAS,
          entryDate: dateStr(8),
          quantity: '480片 / 1,920㎡',
          remark: '第二批进场，现场目测与封样存在轻微色差，待业主确认',
        },
      ],
      confirmRecords: [
        {
          id: generateId('rec'),
          sampleId: '',
          batchId: '',
          action: 'confirm',
          confirmer: '李明',
          confirmerRole: '业主代表',
          confirmerPhone: '13900139001',
          confirmDate: dateStr(45),
          description: '封样确认：样板颜色与建筑整体效果匹配，同意以此为标准批量生产。',
        },
        {
          id: generateId('rec'),
          sampleId: '',
          batchId: '',
          action: 'confirm',
          confirmer: '王工',
          confirmerRole: '幕墙工程师',
          confirmerPhone: '13700137001',
          confirmDate: dateStr(18),
          description: '第一批进场批次 HN-20250315-A1 颜色、厚度、涂层检测均合格，同意进场使用。',
        },
      ],
    },
    {
      id: generateId('sample'),
      sampleNo: 'CW-AL-2025-002',
      version: 'V1.0',
      materialType: '阳极氧化铝板',
      specification: '2.5mm 古铜色 阳极氧化膜厚≥15μm',
      manufacturer: '中联建材科技股份',
      manufacturerContact: '陈主管',
      manufacturerPhone: '13600136001',
      sealPhoto: SEAL_PHOTO_BRONZE,
      sealDate: dateStr(32),
      sealConfirmer: '王工程师（幕墙）',
      remark: '西塔裙楼入口雨篷装饰，需保证色差ΔE<2.0',
      status: 'pending',
      createdAt: ts(35),
      updatedAt: ts(5),
      batches: [
        {
          id: generateId('batch'),
          sampleId: '',
          batchNo: 'ZL-20250508-C',
          entryBatchNo: 'JC-BZ-003',
          entryPhoto: '',
          entryDate: dateStr(3),
          quantity: '180片 / 540㎡',
          remark: '厂家通知已发货，照片尚未上传',
        },
      ],
      confirmRecords: [
        {
          id: generateId('rec'),
          sampleId: '',
          batchId: '',
          action: 'confirm',
          confirmer: '王工',
          confirmerRole: '幕墙工程师',
          confirmerPhone: '13700137001',
          confirmDate: dateStr(32),
          description: '封样确认：颜色均匀，氧化膜厚度检测合格，同意封样。',
        },
      ],
    },
    {
      id: generateId('sample'),
      sampleNo: 'CW-ST-2025-003',
      version: 'V1.2',
      materialType: '石材面板',
      specification: '30mm厚 芝麻灰花岗岩 火烧面',
      manufacturer: '福建石业有限公司',
      manufacturerContact: '林厂长',
      manufacturerPhone: '13500135001',
      sealPhoto: SEAL_PHOTO_STONE,
      sealDate: dateStr(60),
      sealConfirmer: '赵总（设计总监）',
      remark: '北塔基座裙楼1-3层外墙，注意纹理方向一致性',
      status: 'rejected',
      createdAt: ts(65),
      updatedAt: ts(2),
      batches: [
        {
          id: generateId('batch'),
          sampleId: '',
          batchNo: 'FJ-20250420-S1',
          entryBatchNo: 'JC-ST-007',
          entryPhoto: ENTRY_PHOTO_STONE,
          entryDate: dateStr(15),
          quantity: '240片 / 360㎡',
          remark: '退回原因：色差偏大，与封样花色不一致，部分板材存在暗裂纹',
        },
      ],
      confirmRecords: [
        {
          id: generateId('rec'),
          sampleId: '',
          batchId: '',
          action: 'confirm',
          confirmer: '赵总',
          confirmerRole: '设计总监',
          confirmerPhone: '13300133001',
          confirmDate: dateStr(60),
          description: '封样确认：花色、纹理、厚度符合设计要求。',
        },
        {
          id: generateId('rec'),
          sampleId: '',
          batchId: '',
          action: 'reject',
          confirmer: '王工',
          confirmerRole: '幕墙工程师',
          confirmerPhone: '13700137001',
          confirmDate: dateStr(13),
          description: '退回批次 FJ-20250420-S1：现场对比发现色差明显超过样板，约15%板材存在暗裂纹，整批退回厂家更换。',
        },
      ],
    },
    {
      id: generateId('sample'),
      sampleNo: 'CW-GL-2025-004',
      version: 'V3.0',
      materialType: 'Low-E中空玻璃',
      specification: '6+12A+6mm Low-E双银中空钢化',
      manufacturer: '南玻集团华东基地',
      manufacturerContact: '周总监',
      manufacturerPhone: '13400134001',
      sealPhoto: SEAL_PHOTO_GLASS,
      sealDate: dateStr(55),
      sealConfirmer: '李明（业主代表）',
      remark: '标准层外片玻璃，可见光透射比62%，遮阳系数0.38',
      status: 'available',
      createdAt: ts(58),
      updatedAt: ts(25),
      batches: [
        {
          id: generateId('batch'),
          sampleId: '',
          batchNo: 'NB-20250328-G1',
          entryBatchNo: 'JC-GL-002',
          entryPhoto: ENTRY_PHOTO_GLASS,
          entryDate: dateStr(28),
          quantity: '160片 / 576㎡',
          remark: '第三层玻璃，检测报告齐全',
        },
        {
          id: generateId('batch'),
          sampleId: '',
          batchNo: 'NB-20250415-G2',
          entryBatchNo: 'JC-GL-005',
          entryPhoto: ENTRY_PHOTO_GLASS,
          entryDate: dateStr(18),
          quantity: '200片 / 720㎡',
          remark: '第四、五层玻璃，光学性能检测合格',
        },
      ],
      confirmRecords: [
        {
          id: generateId('rec'),
          sampleId: '',
          batchId: '',
          action: 'confirm',
          confirmer: '李明',
          confirmerRole: '业主代表',
          confirmerPhone: '13900139001',
          confirmDate: dateStr(55),
          description: '封样确认：玻璃颜色与设计效果图一致，节能参数达标。',
        },
        {
          id: generateId('rec'),
          sampleId: '',
          batchId: '',
          action: 'confirm',
          confirmer: '王工',
          confirmerRole: '幕墙工程师',
          confirmerPhone: '13700137001',
          confirmDate: dateStr(26),
          description: '批次 NB-20250328-G1 进场验收：玻璃外观、厚度、中空层均符合要求，同意使用。',
        },
      ],
    },
    {
      id: generateId('sample'),
      sampleNo: 'CW-AL-2025-005',
      version: 'V1.0',
      materialType: '粉末喷涂铝板',
      specification: '2mm 珍珠白 阿克苏粉末喷涂',
      manufacturer: '华东装饰材料有限公司',
      manufacturerContact: '吴经理',
      manufacturerPhone: '13200132001',
      sealPhoto: SEAL_PHOTO_AL,
      sealDate: dateStr(12),
      sealConfirmer: '待确认',
      remark: '室内中庭吊顶内衬板，颜色参考样板白-03',
      status: 'pending',
      createdAt: ts(14),
      updatedAt: ts(1),
      batches: [],
      confirmRecords: [],
    },
    {
      id: generateId('sample'),
      sampleNo: 'CW-SS-2025-006',
      version: 'V1.1',
      materialType: '不锈钢板',
      specification: '1.5mm 304不锈钢 拉丝面 香槟金',
      manufacturer: '精工不锈钢制品厂',
      manufacturerContact: '黄工',
      manufacturerPhone: '13100131001',
      sealPhoto: SEAL_PHOTO_BRONZE,
      sealDate: dateStr(38),
      sealConfirmer: '赵总（设计总监）',
      remark: '大堂入口门框及收边条，需做防指纹处理',
      status: 'available',
      createdAt: ts(40),
      updatedAt: ts(20),
      batches: [
        {
          id: generateId('batch'),
          sampleId: '',
          batchNo: 'JG-20250418-SS',
          entryBatchNo: 'JC-SS-001',
          entryPhoto: ENTRY_PHOTO_OK,
          entryDate: dateStr(22),
          quantity: '86件 / 310㎡',
          remark: '首批进场，拉丝纹理均匀，色泽符合封样',
        },
      ],
      confirmRecords: [
        {
          id: generateId('rec'),
          sampleId: '',
          batchId: '',
          action: 'confirm',
          confirmer: '赵总',
          confirmerRole: '设计总监',
          confirmerPhone: '13300133001',
          confirmDate: dateStr(38),
          description: '封样确认：拉丝纹理方向与金色调满意，防指纹效果良好。',
        },
      ],
    },
  ]
}
