import type { Cylinder, StatusHistory, Photo, Approval, SupplementRecord, Anomaly, CylinderStatus } from '@/types';
import { generateId } from './storage';

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
const daysLater = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const createMockCylinders = (): Cylinder[] => {
  const supplementId = 'SUP-MANUAL-001';

  return [
    {
      id: 'CYL-001',
      code: 'XF-2024-001',
      location: 'A栋1层配电室',
      type: '干粉灭火器',
      currentStatus: 'processing' as CylinderStatus,
      pressure: '1.2MPa',
      inspector: '小秦',
      phone: '13800138001',
      lastCheckDate: daysAgo(7),
      nextCheckDate: daysLater(30),
      createdAt: daysAgo(30),
      updatedAt: daysAgo(1),
    },
    {
      id: 'CYL-002',
      code: 'XF-2024-002',
      location: 'B栋2层机房',
      type: '二氧化碳灭火器',
      currentStatus: 'completed' as CylinderStatus,
      pressure: '5.5MPa',
      inspector: '小秦',
      phone: '13800138002',
      lastCheckDate: daysAgo(3),
      nextCheckDate: daysLater(60),
      createdAt: daysAgo(45),
      updatedAt: daysAgo(0),
    },
    {
      id: 'CYL-003',
      code: 'XF-2024-003',
      location: 'C栋3层办公室',
      type: '干粉灭火器',
      currentStatus: 'normal' as CylinderStatus,
      pressure: '1.3MPa',
      inspector: '小李',
      phone: '13800138003',
      lastCheckDate: daysAgo(10),
      nextCheckDate: daysLater(25),
      createdAt: daysAgo(60),
      updatedAt: daysAgo(10),
    },
    {
      id: 'CYL-004',
      code: 'XF-2024-004',
      location: 'D栋负一层车库',
      type: '泡沫灭火器',
      currentStatus: 'overdue' as CylinderStatus,
      pressure: '0.8MPa',
      inspector: '小秦',
      phone: '13800138004',
      lastCheckDate: daysAgo(95),
      nextCheckDate: daysAgo(5),
      createdAt: daysAgo(100),
      updatedAt: daysAgo(95),
    },
    {
      id: 'CYL-005',
      code: 'XF-2024-005',
      location: 'E栋4层档案室',
      type: '七氟丙烷',
      currentStatus: 'inspecting' as CylinderStatus,
      pressure: '2.5MPa',
      inspector: '小张',
      phone: '13800138005',
      lastCheckDate: daysAgo(5),
      nextCheckDate: daysLater(45),
      createdAt: daysAgo(50),
      updatedAt: daysAgo(2),
    },
    {
      id: 'CYL-006',
      code: 'XF-2024-006',
      location: 'F栋5层研发中心',
      type: '干粉灭火器',
      currentStatus: 'repaired' as CylinderStatus,
      pressure: '1.4MPa',
      inspector: '小秦',
      phone: '13800138006',
      lastCheckDate: daysAgo(2),
      nextCheckDate: daysLater(50),
      supplementId,
      createdAt: daysAgo(55),
      updatedAt: daysAgo(1),
    },
  ];
};

export const createMockStatusHistories = (): StatusHistory[] => [
  {
    id: generateId(),
    cylinderId: 'CYL-001',
    oldStatus: 'normal',
    newStatus: 'inspecting',
    operator: '小秦',
    reason: '日常巡检发现压力偏低',
    timestamp: daysAgo(7),
    remark: '压力值1.0MPa，低于标准值1.2MPa',
  },
  {
    id: generateId(),
    cylinderId: 'CYL-001',
    oldStatus: 'inspecting',
    newStatus: 'processing',
    operator: '王主管',
    reason: '现场同事确认已处理',
    timestamp: daysAgo(3),
    remark: '已更换密封垫圈，正在观察',
  },
  {
    id: generateId(),
    cylinderId: 'CYL-002',
    oldStatus: 'normal',
    newStatus: 'inspecting',
    operator: '小秦',
    reason: '月度例行检查',
    timestamp: daysAgo(10),
  },
  {
    id: generateId(),
    cylinderId: 'CYL-002',
    oldStatus: 'inspecting',
    newStatus: 'processing',
    operator: '小秦',
    reason: '发现喷头堵塞',
    timestamp: daysAgo(5),
    remark: '需要清洗喷头',
  },
  {
    id: generateId(),
    cylinderId: 'CYL-002',
    oldStatus: 'processing',
    newStatus: 'completed',
    operator: '王主管',
    reason: '喷头清洗完成，测试正常',
    timestamp: daysAgo(2),
    remark: '现场测试喷射正常',
  },
  {
    id: generateId(),
    cylinderId: 'CYL-004',
    oldStatus: 'normal',
    newStatus: 'overdue',
    operator: '系统',
    reason: '检验周期已逾期',
    timestamp: daysAgo(5),
  },
  {
    id: generateId(),
    cylinderId: 'CYL-005',
    oldStatus: 'normal',
    newStatus: 'inspecting',
    operator: '小张',
    reason: '季度安全检查',
    timestamp: daysAgo(5),
  },
  {
    id: generateId(),
    cylinderId: 'CYL-006',
    oldStatus: 'overdue',
    newStatus: 'repaired',
    operator: '小秦',
    reason: '已完成年检和压力贴纸补录',
    timestamp: daysAgo(1),
    remark: '补录压力值1.4MPa，粘贴新压力贴纸',
  },
];

export const createMockPhotos = (): Photo[] => [
  {
    id: generateId(),
    cylinderId: 'CYL-001',
    url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fire%20extinguisher%20cylinder%20in%20industrial%20power%20room%20inspection%20photo&image_size=square',
    direction: '正面',
    hasDirection: true,
    uploadTime: daysAgo(7),
  },
  {
    id: generateId(),
    cylinderId: 'CYL-001',
    url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fire%20extinguisher%20pressure%20gauge%20close%20up%20photo&image_size=square',
    hasDirection: false,
    missingReason: '巡检照片上传时未选择方向标签，系统无法识别拍摄角度，可能导致班组误判检查位置',
    uploadTime: daysAgo(3),
  },
  {
    id: generateId(),
    cylinderId: 'CYL-002',
    url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=co2%20fire%20extinguisher%20in%20server%20room%20data%20center&image_size=square',
    direction: '左侧',
    hasDirection: true,
    uploadTime: daysAgo(10),
  },
  {
    id: generateId(),
    cylinderId: 'CYL-002',
    url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fire%20extinguisher%20nozzle%20cleaning%20maintenance&image_size=square',
    direction: '特写',
    hasDirection: true,
    uploadTime: daysAgo(2),
  },
  {
    id: generateId(),
    cylinderId: 'CYL-003',
    url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=dry%20powder%20fire%20extinguisher%20in%20office%20corridor&image_size=square',
    direction: '正面',
    hasDirection: true,
    uploadTime: daysAgo(10),
  },
  {
    id: generateId(),
    cylinderId: 'CYL-006',
    url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fire%20extinguisher%20pressure%20sticker%20label%20manual%20supplement&image_size=square',
    direction: '压力贴特写',
    hasDirection: true,
    uploadTime: daysAgo(1),
  },
];

export const createMockApprovals = (): Approval[] => [
  {
    id: 'APR-001',
    cylinderId: 'CYL-001',
    conclusion: '同意更换',
    reason: '气瓶使用年限已达5年，密封件老化导致压力缓慢下降，建议整体更换',
    operator: '李主管',
    role: '安全主管',
    timestamp: daysAgo(6),
    status: 'withdrawn',
  },
  {
    id: 'APR-002',
    cylinderId: 'CYL-001',
    conclusion: '同意维修',
    reason: '现场检查发现仅为密封垫圈老化，无需整体更换，维修即可恢复正常',
    remark: '已联系供应商更换原厂密封垫圈，成本约200元，比更换新气瓶（约1500元）更经济',
    operator: '王主管',
    role: '运维主管',
    timestamp: daysAgo(4),
    status: 'resubmitted',
    parentApprovalId: 'APR-001',
  },
  {
    id: 'APR-003',
    cylinderId: 'CYL-002',
    conclusion: '同意完成',
    reason: '喷头清洗完成，现场测试喷射正常，压力值5.5MPa符合标准',
    operator: '李主管',
    role: '安全主管',
    timestamp: daysAgo(2),
    status: 'submitted',
  },
  {
    id: 'APR-004',
    cylinderId: 'CYL-006',
    conclusion: '确认补录',
    reason: '小秦手工补录的压力贴纸信息真实有效，与现场检查结果一致',
    operator: '王主管',
    role: '运维主管',
    timestamp: daysAgo(1),
    status: 'submitted',
  },
];

export const createMockSupplements = (): SupplementRecord[] => [
  {
    id: 'SUP-PRES-001',
    cylinderId: 'CYL-006',
    type: 'pressure_sticker',
    beforeData: {
      pressure: '未知',
      lastCheckDate: daysAgo(95),
      hasPressureSticker: false,
    },
    afterData: {
      pressure: '1.4MPa',
      lastCheckDate: daysAgo(1),
      hasPressureSticker: true,
      stickerNumber: 'PS-2024-066',
    },
    operator: '小秦',
    timestamp: daysAgo(1),
  },
  {
    id: 'SUP-MANUAL-001',
    cylinderId: 'CYL-006',
    type: 'manual',
    beforeData: {
      status: 'overdue',
      nextCheckDate: daysAgo(5),
      supplementId: undefined,
    },
    afterData: {
      status: 'repaired',
      nextCheckDate: daysLater(50),
      supplementId: 'SUP-MANUAL-001',
      manualEntryNote: '人工补录：完成年检并更新压力贴纸',
    },
    operator: '小秦',
    timestamp: daysAgo(1),
  },
];

export const createMockAnomalies = (): Anomaly[] => [
  {
    id: 'ANOM-001',
    type: 'photo_missing_direction',
    cylinderId: 'CYL-001',
    readableReason: '照片缺少方向说明，可能导致班组误判检查位置。上传的第2张巡检照片未标注拍摄方向（正面/侧面/背面），无法确认是对哪个部位进行检查。',
    technicalDetails: 'Photo ID: PH-xxxx-xxxx, uploadTime: 2024-06-06, direction field is null. The system requires all inspection photos to have direction labels to ensure inspection completeness.',
    detectedAt: daysAgo(3),
    resolved: false,
  },
  {
    id: 'ANOM-002',
    type: 'permission_phone_leak',
    cylinderId: 'CYL-001',
    readableReason: '权限视图配置不当导致手机号泄露。复盘人员在查看历史记录时可以看到巡检人员的完整手机号（138****8001），违反数据脱敏规定，可能导致复盘失真。',
    technicalDetails: 'User role: reviewer, accessed field: phone, expected masking: 138****8001, actual display: 13800138001. Permission check failed for PII fields in review view.',
    detectedAt: daysAgo(2),
    resolved: false,
  },
];

export const getAllMockData = () => ({
  cylinders: createMockCylinders(),
  statusHistories: createMockStatusHistories(),
  photos: createMockPhotos(),
  approvals: createMockApprovals(),
  supplements: createMockSupplements(),
  anomalies: createMockAnomalies(),
});
