[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-dead_strip",
  "-C", "link-arg=-Wl,-S",
  "-C", "link-arg=-Wl,-x",
]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-dead_strip",
  "-C", "link-arg=-Wl,-S",
  "-C", "link-arg=-Wl,-x",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=/OPT:REF",
  "-C", "link-arg=/OPT:ICF",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]
